import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the API Reference docs instance (served at /api-reference).
 * Autogenerated from the symlinked `docs/api/` folder so it always matches the
 * curl-verified source of truth — new endpoint files appear here automatically.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
