import type { team_role } from '@prisma/client';

/**
 * Template/purpose key for an outbound product email. A union rather than a
 * free string so adding a template without registering its type — or renaming
 * one — is a compile error instead of a silently unroutable job.
 */
export type EmailType =
  | 'verify_email'
  | 'password_reset'
  | 'welcome'
  | 'password_changed'
  | 'new_sign_in'
  | 'team_invite'
  | 'budget_threshold'
  | 'budget_exhausted'
  | 'eval_run_finished'
  | 'member_joined'
  | 'member_removed'
  | 'member_roles_changed'
  | 'weekly_digest';

/** Lifecycle of an `email_log` row. */
export type EmailLogStatus = 'queued' | 'sent' | 'failed';

/** An `email_log` row as read back from the database. */
export interface EmailLogRow {
  id: string;
  teamId: string;
  type: string;
  toEmail: string;
  subject: string;
  status: string;
  providerMessageId: string | null;
  error: string | null;
  createdAt: Date;
  sentAt: Date | null;
}

/** A fully rendered message, ready for a transport. */
export interface EmailMessage {
  /** Single recipient address. One message per recipient — no bulk envelopes. */
  to: string;
  /** RFC 5322 `From`, e.g. `acruxcore <no-reply@acruxcore.com>`. */
  from: string;
  /** Optional `Reply-To`; the shared support inbox in practice. */
  replyTo?: string;
  subject: string;
  html: string;
  text: string;
  /**
   * Extra RFC 5322 headers. Used for RFC 8058 one-click unsubscribe
   * (`List-Unsubscribe` + `List-Unsubscribe-Post`), which Gmail and Yahoo require
   * of bulk senders and which a body link alone does not satisfy.
   */
  headers?: Record<string, string>;
}

/** What a template returns: the two bodies, a subject, and any extra headers. */
export interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
  /** See {@link EmailMessage.headers}. Only the digest sets these today. */
  headers?: Record<string, string>;
}

/**
 * A send that can never succeed — a malformed or suppressed address, a
 * rejected message, a suspended account.
 *
 * Exists to keep BullMQ from burning five attempts and 75 seconds of backoff
 * on a message no retry can deliver: `processEmail` converts this into
 * BullMQ's `UnrecoverableError`, while every other error propagates as
 * retryable.
 */
export class EmailPermanentError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'EmailPermanentError';
  }
}

/**
 * Props for the two account-security emails (verify address, reset password).
 *
 * Both carry a single-use link and nothing else. Neither takes an
 * `unsubscribeUrl`: they are not notifications a user can decline — turning off
 * "you can now reset your password" would lock people out of their own accounts
 * — so they deliberately bypass the notification-preference machinery.
 */
export interface AuthLinkEmailProps {
  /**
   * Absolute, single-use URL on our own domain. Generated by Better Auth, which
   * embeds the token; consuming it deletes the `auth_verifications` row, so the
   * link cannot be replayed.
   */
  url: string;
  /** Minutes until the link expires, for the body copy. */
  expiresInMinutes: number;
}

/** Props for the welcome email, sent once the address is confirmed. */
export interface WelcomeEmailProps {
  /** Where to land the new user — their prompt list. */
  dashboardUrl: string;
  /** Their own team's name, so the email reflects the workspace they landed in. */
  teamName: string;
}

/**
 * Props for the "your password was changed" confirmation.
 *
 * Sent after a completed reset, not before — it is the notification that tells
 * someone their account was taken over, so it must describe a change that has
 * already happened.
 */
export interface PasswordChangedEmailProps {
  /** ISO timestamp of the change. */
  changedAt: string;
  /** Where to start another reset, if this was not them. */
  resetUrl: string;
}

/** Props for the new-device sign-in alert. */
export interface NewSignInEmailProps {
  /** ISO timestamp of the sign-in. */
  signedInAt: string;
  /** Requesting IP, or null when the proxy did not supply one. */
  ipAddress: string | null;
  /** Raw user-agent, or null. Rendered as-is and escaped — never parsed. */
  userAgent: string | null;
  /** Where to reset the password if this sign-in was not theirs. */
  resetUrl: string;
}

/** Props for the team invite email. */
export interface TeamInviteEmailProps {
  /** Team the recipient is being invited to. User-supplied — must be escaped. */
  teamName: string;
  /** Display name of the inviter, or their email when no display name is set. */
  inviterName: string;
  /** Role the invite grants, e.g. `'editor'`. */
  role: team_role;
  /** Absolute accept URL, built from `APP_URL` — never a relative path. */
  inviteUrl: string;
  /**
   * When the invite stops working, ISO 8601. A string rather than a `Date`
   * because this object round-trips through Redis as JSON, which would hand
   * the worker a string regardless.
   */
  expiresAt: string;
}

/**
 * Props shared by both budget alerts — the 80% warning and the 100% exhausted
 * notice say the same things about the same row, differing only in tone.
 */
export interface BudgetAlertEmailProps {
  /** Team the budget belongs to. User-supplied — must be escaped. */
  teamName: string;
  /** `Team-wide` or `Virtual key "<name>"`. Contains a user-supplied key name. */
  scopeLabel: string;
  /** Reset cadence: `day` | `week` | `month` | `total`. */
  period: string;
  /** Cap in USD. */
  limitUsd: number;
  /** Spend in USD at the moment the threshold was crossed. */
  spendUsd: number;
  /** Absolute link to the budgets screen. */
  budgetsUrl: string;
  /** Absolute link that turns this category off for the recipient. */
  unsubscribeUrl: string;
}

/** Props for the eval-run-finished email. */
export interface EvalRunFinishedEmailProps {
  /** Team the run belongs to. User-supplied — must be escaped. */
  teamName: string;
  /** Experiment name, or a fallback when the experiment is unnamed. */
  experimentName: string;
  /** Terminal status of the run. */
  outcome: 'succeeded' | 'failed';
  /** Cells that produced a result without an error. */
  succeededCells: number;
  /** Cells that recorded a terminal error. */
  erroredCells: number;
  /**
   * Wall-clock run duration in seconds, or null when `startedAt`/`endedAt` are
   * not both set (a run that never started cannot be timed).
   */
  durationSeconds: number | null;
  /** Absolute deep link to the run. */
  runUrl: string;
  /** Absolute link that turns this category off for the recipient. */
  unsubscribeUrl: string;
}

/** Props shared by the three membership emails. */
export interface MembershipEmailProps {
  /** Team the change happened in. User-supplied — must be escaped. */
  teamName: string;
  /** Display name (or email) of the member the change is about. */
  memberName: string;
  /** Display name (or email) of whoever made the change. */
  actorName: string;
  /** The member's role after the change. Null for `member_removed`. */
  role: team_role | null;
  /** Absolute link to the team screen. */
  teamUrl: string;
  /** Absolute link that turns this category off for the recipient. */
  unsubscribeUrl: string;
}

/** One `(label, value)` row in the digest's headline table. */
export interface DigestStat {
  /** Row label, e.g. `Gateway spend`. Never user-supplied. */
  label: string;
  /** Pre-formatted value, e.g. `$12.40`. Formatted before it reaches the template. */
  value: string;
  /**
   * Pre-formatted week-over-week change, e.g. `+18% vs last week`. Undefined
   * for rows where a trend is not computed.
   */
  delta?: string;
}

/** Props for the weekly usage digest. */
export interface WeeklyDigestEmailProps {
  /** Team the digest summarises. User-supplied — must be escaped. */
  teamName: string;
  /** Window start, `YYYY-MM-DD`. */
  fromDate: string;
  /** Window end (inclusive day), `YYYY-MM-DD`. */
  toDate: string;
  /** Headline numbers, already formatted. */
  stats: DigestStat[];
  /** Top models by spend, already formatted and capped at five. */
  topModels: { model: string; value: string }[];
  /** Budget lines, already formatted. Empty when the team has no budgets. */
  budgets: { scope: string; value: string }[];
  /** Absolute link to the usage screen. */
  usageUrl: string;
  /** Absolute one-click unsubscribe link for `weekly_digest` in this team. */
  unsubscribeUrl: string;
}

/**
 * A template key paired with its own props. Discriminated on `type`, so
 * `renderEmail`'s switch is exhaustive and a new `EmailType` without a template
 * fails to compile.
 */
export type EmailPayload =
  | { type: 'verify_email'; props: AuthLinkEmailProps }
  | { type: 'password_reset'; props: AuthLinkEmailProps }
  | { type: 'welcome'; props: WelcomeEmailProps }
  | { type: 'password_changed'; props: PasswordChangedEmailProps }
  | { type: 'new_sign_in'; props: NewSignInEmailProps }
  | { type: 'team_invite'; props: TeamInviteEmailProps }
  | { type: 'budget_threshold'; props: BudgetAlertEmailProps }
  | { type: 'budget_exhausted'; props: BudgetAlertEmailProps }
  | { type: 'eval_run_finished'; props: EvalRunFinishedEmailProps }
  | { type: 'member_joined'; props: MembershipEmailProps }
  | { type: 'member_removed'; props: MembershipEmailProps }
  | { type: 'member_roles_changed'; props: MembershipEmailProps }
  | { type: 'weekly_digest'; props: WeeklyDigestEmailProps };
